# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-24 09:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item_master', '0002_auto_20180822_2133'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80, unique=True)),
                ('code', models.CharField(blank=True, max_length=30, null=True)),
                ('add1', models.CharField(blank=True, max_length=100, null=True)),
                ('add2', models.CharField(blank=True, max_length=100, null=True)),
                ('add3', models.CharField(blank=True, max_length=100, null=True)),
                ('contact1', models.CharField(blank=True, max_length=12, null=True)),
                ('contact2', models.CharField(blank=True, max_length=12, null=True)),
                ('contact3', models.CharField(blank=True, max_length=12, null=True)),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80, unique=True)),
                ('person', models.CharField(blank=True, max_length=150, null=True)),
                ('add1', models.CharField(blank=True, max_length=100, null=True)),
                ('add2', models.CharField(blank=True, max_length=100, null=True)),
                ('add3', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('phone1', models.CharField(blank=True, max_length=12, null=True)),
                ('phone2', models.CharField(blank=True, max_length=12, null=True)),
                ('use_date', models.DateField(blank=True, null=True)),
                ('use_time', models.TimeField(blank=True, null=True)),
                ('less_by', models.IntegerField(blank=True, default=0, null=True)),
                ('identity', models.CharField(blank=True, max_length=30, null=True)),
                ('account_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Accounts')),
                ('head_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Head')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvDtl',
            fields=[
                ('sequence', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('batch_no', models.CharField(db_index=True, max_length=15)),
                ('strip_qty', models.IntegerField(blank=True, default=0)),
                ('nos_qty', models.IntegerField(blank=True, default=0)),
                ('strip_free', models.IntegerField(blank=True, default=0)),
                ('nos_free', models.IntegerField(blank=True, default=0)),
                ('disc_type', models.CharField(choices=[('Rs', 'Rs'), ('Percent', '%')], default='Percent', max_length=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6)),
                ('disc_amt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6)),
                ('excise_type', models.CharField(choices=[('Rs', 'Rs'), ('Percent', '%')], default='Percent', max_length=10)),
                ('excise', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6)),
                ('excise_amt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6)),
                ('st_rate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6)),
                ('scharge_rate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6)),
                ('sgst_amt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6)),
                ('cgst_amt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6)),
                ('other_charge', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8)),
                ('td', models.IntegerField(blank=True, default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvHrd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_no', models.IntegerField(blank=True, db_index=True, null=True)),
                ('doc_dt', models.DateField(default=django.utils.timezone.now)),
                ('message', models.CharField(blank=True, max_length=300, null=True)),
                ('mode', models.CharField(choices=[('CASH', 'CASH'), ('CREDIT', 'CREDIT'), ('BANK', 'BANK')], default='CASH', max_length=10)),
                ('sale_discount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6)),
                ('sale_disc_type', models.CharField(choices=[('Rs', 'Rs'), ('Percent', '%')], default='Percent', max_length=10)),
                ('sale_adjustment', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('rec_amt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('net_cgst', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8)),
                ('net_sgst', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8)),
                ('net_gst', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8)),
                ('due_amt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6)),
                ('use_date', models.DateField(blank=True, null=True)),
                ('use_time', models.TimeField(blank=True, null=True)),
                ('ref_note', models.CharField(blank=True, max_length=50, null=True)),
                ('note_value', models.IntegerField(blank=True, default=0)),
                ('token', models.IntegerField(blank=True, default=0)),
                ('opd', models.CharField(blank=True, max_length=50, null=True)),
                ('doctor_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales.Doctor')),
                ('party_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales.Party')),
                ('session_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.YearEnding')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='salesinvdtl',
            name='hrd_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.SalesInvHrd'),
        ),
        migrations.AddField(
            model_name='salesinvdtl',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_master.Item'),
        ),
        migrations.AlterUniqueTogether(
            name='salesinvhrd',
            unique_together=set([('doc_no', 'session_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='salesinvdtl',
            unique_together=set([('hrd_id', 'item_id', 'batch_no')]),
        ),
    ]
