# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-15 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_master', '0003_supplier_gst_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='dl_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='gst_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
