# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-15 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_master', '0004_auto_20181015_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='dl_no',
        ),
    ]
