# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-23 11:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('company_master', '0002_auto_20180822_2159'),
        ('item_master', '0002_auto_20180822_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvDtl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(db_index=True, max_length=15)),
                ('strip_qty', models.IntegerField(blank=True, default=0)),
                ('nos_qty', models.IntegerField(blank=True, default=0)),
                ('strip_free', models.IntegerField(blank=True, default=0)),
                ('nos_free', models.IntegerField(blank=True, default=0)),
                ('disc_type', models.CharField(choices=[('Percent', '%')], default='Percent', max_length=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('disc_amt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6)),
                ('excise_type', models.CharField(choices=[('Percent', '%')], default='Percent', max_length=10)),
                ('excise', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6)),
                ('excise_amt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6)),
                ('st_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('other_charge', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6)),
                ('cgst', models.CharField(choices=[('0', '0'), ('2.5', '2.5'), ('6', '6'), ('9', '9'), ('14', '14')], default='6', max_length=3)),
                ('sgst', models.CharField(choices=[('0', '0'), ('2.5', '2.5'), ('6', '6'), ('9', '9'), ('14', '14')], default='6', max_length=3)),
                ('sgst_type', models.CharField(choices=[('Percent', '%')], default='Percent', max_length=10)),
                ('cgst_type', models.CharField(choices=[('Percent', '%')], default='Percent', max_length=10)),
                ('sgst_amt', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('cgst_amt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6)),
                ('scharge_rate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8)),
                ('td', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInvHrd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_no', models.IntegerField(blank=True, db_index=True, null=True)),
                ('doc_dt', models.DateField(default=django.utils.timezone.now)),
                ('p_method', models.CharField(choices=[('CASH', 'CASH'), ('CREDIT', 'CREDIT'), ('BANK', 'BANK')], default='CASH', max_length=50)),
                ('supp_chal_no', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('supp_chal_dt', models.DateField(default=django.utils.timezone.now)),
                ('net_discount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6)),
                ('net_cgst', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6)),
                ('net_sgst', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6)),
                ('net_adj', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paid_discount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6)),
                ('paid_cgst', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6)),
                ('paid_sgst', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6)),
                ('paid_adj', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6)),
                ('paid_adj_type', models.CharField(choices=[('Positive', '+'), ('Nagetive', '-')], default='Positive', max_length=10)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('use_date', models.DateField(blank=True, null=True)),
                ('use_time', models.TimeField(blank=True, null=True)),
                ('due_amt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8)),
                ('ref_note', models.CharField(blank=True, max_length=80, null=True)),
                ('session_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.YearEnding')),
                ('supplier_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company_master.Supplier')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='purchaseinvdtl',
            name='hrd_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.PurchaseInvHrd'),
        ),
        migrations.AddField(
            model_name='purchaseinvdtl',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_master.Item'),
        ),
    ]
