# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-23 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchaseinvhrd',
            unique_together=set([('session_id', 'doc_no')]),
        ),
    ]
