# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-23 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('company_master', '0002_auto_20180822_2159'),
        ('purchase', '0002_auto_20180823_1800'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchaseinvhrd',
            unique_together=set([('supplier_id', 'supp_chal_no', 'session_id'), ('session_id', 'doc_no')]),
        ),
    ]
