# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-24 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_master', '0002_auto_20180822_2133'),
        ('purchase', '0003_auto_20180823_1902'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchaseinvdtl',
            unique_together=set([('hrd_id', 'item_id', 'batch_no')]),
        ),
    ]
