# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-07 08:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unit_master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company_master', '0001_initial'),
        ('godown_master', '0001_initial'),
        ('salt_master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=15)),
                ('strip', models.IntegerField(blank=True, default=0, null=True)),
                ('nos', models.IntegerField(blank=True, default=0, null=True)),
                ('expiry', models.DateField()),
                ('strip_pur', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True)),
                ('strip_sale', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True)),
                ('sale_rt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True)),
                ('inst_rt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True)),
                ('trade_rt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True)),
                ('std_rt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True)),
                ('pur_rt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True)),
                ('tot_rec_qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('tot_iss_qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('conv', models.IntegerField(blank=True, null=True)),
                ('td', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('min_qty', models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=8, null=True)),
                ('max_qty', models.DecimalField(blank=True, decimal_places=2, default=20, max_digits=8, null=True)),
                ('re_level', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('re_qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('nac', models.IntegerField(blank=True, default=0, null=True)),
                ('slow_days', models.IntegerField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('strip_stock', models.IntegerField(blank=True, default=0, null=True)),
                ('nos_stock', models.IntegerField(blank=True, default=0, null=True)),
                ('bin_no', models.CharField(blank=True, max_length=10, null=True)),
                ('sgst', models.CharField(choices=[('0', '0'), ('2.5', '2.5'), ('6', '6'), ('9', '9'), ('14', '14')], default='6', max_length=3)),
                ('cgst', models.CharField(choices=[('0', '0'), ('2.5', '2.5'), ('6', '6'), ('9', '9'), ('14', '14')], default='6', max_length=3)),
                ('use_date', models.DateField(blank=True, null=True)),
                ('use_time', models.TimeField(blank=True, null=True)),
                ('app', models.BooleanField(default=False)),
                ('company_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company_master.Company')),
                ('godown_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='godown_master.Godown')),
                ('group_id', models.ForeignKey(default=37, on_delete=django.db.models.deletion.CASCADE, to='company_master.Chain')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='TaxType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('desc', models.CharField(max_length=50)),
                ('applicable', models.CharField(choices=[('Sale', 'Sale'), ('Purchase', 'Purchase')], max_length=10)),
                ('cst_rt', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('lst_rt', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('surcharge_rt', models.IntegerField(default=0)),
                ('add_sur', models.IntegerField(default=0)),
                ('ac', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_ac', models.CharField(blank=True, max_length=50, null=True)),
                ('calc_on', models.CharField(default='AFTER DISCOUNT', max_length=50)),
                ('use_date', models.DateField(blank=True, null=True)),
                ('use_time', models.TimeField(blank=True, null=True)),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TaxType',
                'verbose_name_plural': 'TaxTypes',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='ptax_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='PurchaseTax', to='item_master.TaxType'),
        ),
        migrations.AddField(
            model_name='item',
            name='salt_id',
            field=models.ForeignKey(default=715, on_delete=django.db.models.deletion.CASCADE, to='salt_master.Salt'),
        ),
        migrations.AddField(
            model_name='item',
            name='stax_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ServiceTax', to='item_master.TaxType'),
        ),
        migrations.AddField(
            model_name='item',
            name='unit_id',
            field=models.ForeignKey(default=601, on_delete=django.db.models.deletion.CASCADE, to='unit_master.Unit'),
        ),
        migrations.AddField(
            model_name='item',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batch',
            name='item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item_master.Item'),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together=set([('batch_no', 'item_id')]),
        ),
    ]
