# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-22 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_no',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(db_index=True, max_length=80, unique=True),
        ),
    ]
